### ISSUE TITLE
Error in running script start_demo.sh

### ISSUE THREAD

**Issue by sl950313** [cmusatyalab/faceswap#6] opened 2017-11-01 07:37 UTC
Error occurs in running the script, it seems the link is old. following is the output of running the script, please give me help. thank you!
```
sourcing torch: 
/home/root/torch/install/bin/torch-activate
start_demo.sh: 6: start_demo.sh: source: not found
start_demo.sh: 17: start_demo.sh: Bad substitution
DIR=/root/sl/faceswap/server
-e start downloading models


====================================================
Downloading OpenFace models, which are copyright
Carnegie Mellon University and are licensed under
the Apache 2.0 License.

This will incur about 100MB of network traffic for the models.
====================================================

http://openface-models.storage.cmusatyalab.org/nn4.small2.v1.t7:
2017-11-01 15:28:20 ERROR 404: Not Found.
+ nn4.small2.v1.t7: Error in wget.
http://openface-models.storage.cmusatyalab.org/celeb-classifier.nn4.small2.v1.pkl:
2017-11-01 15:28:21 ERROR 404: Not Found.
+ celeb-classifier.nn4.small2.v1.pkl: Error in wget.


====================================================
Verifying checksums.
====================================================

+ dlib/shape_predictor_68_face_landmarks.dat: successfully checked

md5sum: openface/celeb-classifier.nn4.small2.v1.pkl: No such file or directory
/root/sl/faceswap/server/openface-server/models/get-models.sh: line 74: [: 199a2c0d32fd0f22f14ad2d248280475: unary operator expected
+ ERROR! openface/celeb-classifier.nn4.small2.v1.pkl md5sum did not match.
  + Expected: 199a2c0d32fd0f22f14ad2d248280475
  + Actual: 
  + Please manually delete this file and try re-running this script.
-e launching FaceSwap server at dir /root/sl/faceswap/server
start_demo.sh: 29: start_demo.sh: gabriel-control: not found
start_demo.sh: 32: start_demo.sh: gabriel-ucomm: not found
Traceback (most recent call last):
  File "/root/sl/faceswap/server/openface-server/cloudlet-demo-openface-server.py", line 25, in <module>
    import txaio
ImportError: No module named txaio
checking openface server status:
1
openface server has not finished starting. wait for another 20 seconds...

```

**Comment by sl950313** [comment] 2017-11-01 07:43
I found a link in the github page of openface , and the right link should be https not the http.

**Comment by jaharkes** [comment] 2017-11-01 12:48
This was caused by a configuration error on some of the radosgw backends. It should be fixed now.

**Closed by jaharkes** 2017-11-01 12:48 UTC
